[tool.pyright]
include = [
    "nameless",
    "tests",
    "NamelessConfig_example.py",
    "NamelessConfig.py",
    "main.py",
]
exclude = [
    "alembic",
    "**/__pycache__",
]

reportUnnecessaryTypeIgnoreComment = "warning"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportUnusedImport = "error"
useLibraryCodeForTypes = true
pythonVersion = "3.8"
typeCheckingMode = "basic"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120
lines_after_imports = 2
force_grid_wrap = 2
multi_line_output = 3

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
