[tool.pyright]
include = [
    "cogs",
    "customs",
    "database",
    "./config.example.py",
    "./main.py",
]
exclude = [
    "alembic",
    "**/__pycache__",
]

reportUnnecessaryTypeIgnoreComment = "warning"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportUnusedImport = "error"
pythonVersion = "3.8"
typeCheckingMode = "off"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
max_line_length = 120