[tool.pyright]
include = [
    "nameless",
    "tests",
    "config_example.py",
    "main.py",
]
exclude = [
    "alembic",
    "**/__pycache__",
]

reportUnnecessaryTypeIgnoreComment = "warning"
reportOptionalMemberAccess = "warning"
reportOptionalSubscript = "warning"
reportUnusedImport = "error"
useLibraryCodeForTypes = true
pythonVersion = "3.8"
typeCheckingMode = "basic"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120
