name: anything-python

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', 'pypy-3.8', '3.x' ]
        language: [ 'en' ]

    name: CI on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools wheel requests "aiohttp>=3.7.4,<4"
          pip install -U -r requirements_core.txt
          pip install -U -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          mv config.example.py config.py

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: '1.1.242'
          warnings: false
          no-comments: false

      - name: Run black
        run: |
          black . --check --diff
