name: anything python

on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - main
      - dev
  pull_request:
    tags-ignore:
      - "*.*"
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  dev-run:
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    name: Dev instance test, lint and publish
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt
          pip install -U -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp NamelessConfig_example.py NamelessConfig.py

      - name: Run Pyright
        run: |
          pyright

      - name: Run flake8
        run: |
          flake8 --select=E

      - name: Run pylint
        run: |
          pylint **/*.py --disable=W,R,C

      - name: Run black
        run: |
          black . --check --diff

      - name: Run tests and return coverages
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.commons.Utility tests/

      - name: Deploy to server (dev)
        run: |
          sudo apt install sshpass -y
          echo pm2 restart ${{ secrets.INSTANCE_NAME }} > script.sh
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash -s" < script.sh > /dev/null

  stable-publish:
    runs-on: ubuntu-latest
    name: Stable instance publish
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to server (stable)
        run: |
          sudo apt install sshpass -y
          echo pm2 restart ${{ secrets.STABLE_INSTANCE_NAME }} > script.sh
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash -s" < script.sh > /dev/null
