name: everything python

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: CI on Python 3.8
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        id: install-deps
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt
          pip install -U -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp config_example.py config.py

      - name: Run Pyright
        run: |
          pyright

      - name: Run flake8
        run: |
          flake8

      - name: Run pylint
        run: |
          pylint **/*.py --disable=W,R,C

      - name: Run black
        run: |
          black . --check --diff

      - name: Run tests and return coverages
        run: |
          pytest --cov-report term-missing --cov=nameless.database --cov=nameless.customs.Utility tests/

      - name: Deploy to server
        run: |
          sudo apt install sshpass -y
          echo pm2 restart ${{ secrets.INSTANCE_NAME }} > script.sh
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash -s" < script.sh > /dev/null
