name: anything-python

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', 'pypy-3.8' ]

    name: CI on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -U -r requirements_core.txt
          pip install -U -r requirements_dev.txt

      - name: Create dummy config file
        run: |
          cp config.example.py config.py

      - name: Run Pyright
        run: |
          pyright

      - name: Run flake8
        run: |
          flake8

      - name: Run pylint
        run: |
          pylint **/*.py --disable=W,R,C

      - name: Run black
        run: |
          black . --check --diff

      - name: Run tests and return coverages
        run: |
          pytest --cov-report term-missing --cov=database --cov=customs.Utility tests/

      - name: Deploy to server
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          sudo apt install sshpass -y
          echo pm2 restart ${{ secrets.INSTANCE_NAME }} > script.sh
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash -s" < script.sh > /dev/null
